"""Channel metadata: labels, the metric that drives each channel's status,
and which series to chart. One entry per dashboard tab."""
from __future__ import annotations

# channel_key -> config
CHANNELS: dict[str, dict] = {
    "cliniko": {
        "source": "cliniko",
        "label": "Cliniko – New Patients",
        "description": (
            "The North Star source: first-ever paid appointment, counted at point "
            "of booking. Combined and split by Dublin 2 / Dublin 7."
        ),
        "primary_metric": "new_patients",
        "primary_unit": "patients",
        "has_milestone": True,
        "higher_is_better": True,
        "trend_keys": [["new_patients", "New patients / week"]],
    },
    "google_ads": {
        "source": "google_ads",
        "label": "Google Ads",
        "description": "Active search campaigns: spend, clicks, conversions and cost efficiency.",
        "primary_metric": "conversions",
        "primary_unit": "conversions",
        "has_milestone": False,
        "higher_is_better": True,
        "trend_keys": [["spend", "Spend (€)"], ["conversions", "Conversions"]],
    },
    "meta": {
        "source": "meta",
        "label": "Facebook & Instagram",
        "description": "Active Meta campaigns: spend, reach, leads and cost per lead.",
        "primary_metric": "leads",
        "primary_unit": "leads",
        "has_milestone": False,
        "higher_is_better": True,
        "trend_keys": [["spend", "Spend (€)"], ["leads", "Leads"]],
    },
    "youtube": {
        "source": "youtube",
        "label": "YouTube Ads",
        "description": "Video campaigns (run through Google Ads): views, view rate and cost per view.",
        "primary_metric": "views",
        "primary_unit": "views",
        "has_milestone": False,
        "higher_is_better": True,
        "trend_keys": [["spend", "Spend (€)"], ["views", "Views"]],
    },
    "gbp": {
        "source": "gbp",
        "label": "Google Business Profile",
        "description": "Both locations: reviews, rating, profile views, calls and directions.",
        "primary_metric": "new_reviews",
        "primary_unit": "new reviews",
        "has_milestone": False,
        "higher_is_better": True,
        "trend_keys": [["reviews_total", "Total reviews"], ["new_reviews", "New reviews"]],
    },
    "seo": {
        "source": "ga4",
        "label": "Website & SEO",
        "description": "GA4 traffic by source/medium with key conversions (callbacks, bookings, info packs).",
        "primary_metric": "sessions",
        "primary_unit": "sessions",
        "has_milestone": False,
        "higher_is_better": True,
        "trend_keys": [["sessions", "Sessions"], ["conversions", "Key conversions"]],
    },
    "funnel": {
        "source": "ghl",
        "label": "Funnel (GoHighLevel)",
        "description": "Leads by source and injury type, pipeline stages and lead-to-patient rate.",
        "primary_metric": "patients",
        "primary_unit": "new patients",
        "has_milestone": False,
        "higher_is_better": True,
        "trend_keys": [["leads", "Leads"], ["patients", "New patients"]],
    },
}

# Friendly labels + formatting hints for individual metrics.
METRIC_META: dict[str, dict] = {
    "new_patients": {"label": "New patients", "unit": "", "fmt": "int"},
    "spend": {"label": "Spend", "unit": "€", "fmt": "money"},
    "impressions": {"label": "Impressions", "unit": "", "fmt": "int"},
    "reach": {"label": "Reach", "unit": "", "fmt": "int"},
    "clicks": {"label": "Clicks", "unit": "", "fmt": "int"},
    "conversions": {"label": "Conversions", "unit": "", "fmt": "dec1"},
    "bookings": {"label": "Bookings", "unit": "", "fmt": "dec1"},
    "leads": {"label": "Leads", "unit": "", "fmt": "dec1"},
    "cost_per_conversion": {"label": "Cost / conversion", "unit": "€", "fmt": "money"},
    "cost_per_lead": {"label": "Cost / lead", "unit": "€", "fmt": "money"},
    "conversion_rate": {"label": "Conversion rate", "unit": "%", "fmt": "pct"},
    "views": {"label": "Views", "unit": "", "fmt": "int"},
    "view_rate": {"label": "View rate", "unit": "%", "fmt": "pct"},
    "cost_per_view": {"label": "Cost / view", "unit": "€", "fmt": "money3"},
    "profile_views": {"label": "Profile views", "unit": "", "fmt": "int"},
    "searches": {"label": "Searches", "unit": "", "fmt": "int"},
    "calls": {"label": "Calls", "unit": "", "fmt": "int"},
    "direction_requests": {"label": "Direction requests", "unit": "", "fmt": "int"},
    "website_clicks": {"label": "Website clicks", "unit": "", "fmt": "int"},
    "new_reviews": {"label": "New reviews", "unit": "", "fmt": "int"},
    "reviews_total": {"label": "Total reviews", "unit": "", "fmt": "int"},
    "rating_avg": {"label": "Average rating", "unit": "★", "fmt": "dec2"},
    "sessions": {"label": "Sessions", "unit": "", "fmt": "int"},
    "users": {"label": "Users", "unit": "", "fmt": "int"},
    "request_callback": {"label": "Request a call back", "unit": "", "fmt": "dec1"},
    "book_online_clicks": {"label": "Book online clicks", "unit": "", "fmt": "dec1"},
    "info_pack_downloads": {"label": "Info pack downloads", "unit": "", "fmt": "dec1"},
    "qualified": {"label": "Qualified", "unit": "", "fmt": "int"},
    "booked": {"label": "Assessment booked", "unit": "", "fmt": "int"},
    "patients": {"label": "New patients", "unit": "", "fmt": "dec1"},
}
